
##########################################################

##--      Convo Meta Feature Generation               --##

## variable list

# wait time in a queue
# texter initial response time
# severity of issues
# time length of convo
# total message length of convo: nms.all
# total message length of texter: nms.texter
# total message length of counselor: nms.counselor
# total message ratio texter/counselor: nms.tcratio
# average response time: conv_length/nms.all
# texter chronicity
#
# counselor response time: conv_length.counselor/nms.counselor
# texter response time: conv_length.texter/nms.texter
# texter issue


##########################################################

rm(list=ls())

## set working directory
setwd("C:/School/Thesis")

## read in data
load("./data/convo_rated_cleaned.Rda") 
# load("./data/ms_rated_cleaned.Rda")


## convo time length
convo$conv_length <- as.numeric(convo$conv_end - convo$queue_exit)

## texter wait time in queue
convo$wait_queue <- as.numeric(convo$queue_exit - convo$queue_enter)

## texter finish system questions (initial response)
convo$texter_initial <- as.numeric(convo$queue_enter - convo$conv_start)

## severity of issues
severity <- numeric(length=nrow(convo))

for (i in 1:length(severity)){
  if (grepl("yes",convo$Q75_active_rescue[i]) |
        grepl("rescue",convo$Q8_conv_resolution[i])){
    severity[i] <- 5
  }else if(grepl("in_progress",convo$Q66_suicidal_intent[i])){
    severity[i] <- 4
  }else if(grepl("suicide_plan",convo$Q66_suicidal_intent[i]) |
             grepl("suicide_timeframe",convo$Q66_suicidal_intent[i]) |
             grepl("suicide_prep",convo$Q66_suicidal_intent[i]) |
             grepl("suicide_expressed_intent",convo$Q66_suicidal_intent[i]) |
             !is.na(convo$Q67_suicidal_capability[i])){
    severity[i] <- 3
  }else if(!is.na(convo$Q66_suicidal_intent[i])){
    severity[i] <- 2
  }else if(grepl("suicide",convo$Q13_issues[i])){
    severity[i] <- 1
  }else{
    severity[i] <- NA
  }
}

unique(severity)
convo$severity <- severity

## texter chronicity
require(plyr)

texter_chronicity <- ddply(convo, .(texter_id), nrow)
colnames(texter_chronicity) <- c("texter_id", "texter.frequency")
convo <- merge(x = texter_chronicity, y = convo, by.x = "texter_id", by.y = "texter_id")
convo$texter_chronicity <-  "new"
convo$texter_chronicity[convo$texter.frequency > 1 & convo$texter.frequency < 20] <-  "repeat"
convo$texter_chronicity[convo$texter.frequency >= 20] <-  "chronic"
unique(convo$texter_chronicity)


## the code below requires merge of convo $ ms dataset
load("./data/convo_lan_meta.Rda")
  ## generated by MessageAggregation.R


## convo total message, texter total message, counselor total message, tc total message ratio
convo <- merge(x = convo_lan_meta[,-c(2,5)], y = convo, by.x = "conv_id", by.y = "conv_id")

## conversation actor average response time 
convo$aveRes <- convo$conv_length/convo$nms.all


## save
save(convo, file = "./data/convo_meta_feature.Rda")


## ------------------------ code for future use

## counselor average response time
count_response <- function(data){
  data <- data[order(data$m_time), ]
  index.c <- which(data$type=="counselor") 
  #print(index.c)
  c.s <- index.c[1]
  #print(c.s)
  c.e <- index.c[length(index.c)]
  #print(c.e)
  
  index.t <- which(data$type=="texter")
  #print(index.t)
  if(!any(index.t > c.s)){
    return("Not Engaged")
  }else{
    start <- min(which(index.t > c.s))
    #print(start)
    end <- max(which(index.t < c.e))
    #print(end)
    range <- index.t[start:end]
    #print(range)
    
    minute = 0
    count = 0
    for (i in range){
      for (j in i+1:range[length(range)]){
        if(data$type[j]=="counselor"){
          minute = minute + as.numeric(data$m_time[j]-data$m_time[i])
          #print(minute)
          count=count+1
          #print(count)
        }
        break
      }   
    }
    return(minute/count)
  }
}

result <- ddply(ms,.(conv_id),count_response)


